# Generated by Django 5.1.1 on 2024-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.UUIDField(default='<function uuid4 at 0x7f72b7b6f100>', editable=False, unique=True),
        ),
    ]
