# Generated by Django 5.1.1 on 2024-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
